### ISSUE TITLE
update submodule for boost

### ISSUE THREAD

**Issue by tonyliu1** [tobiasrausch/tenX#1]
Hi Tobias,

I want to install the tenX following your installation steps. Everything goes find expect when I updated the submodule of modular-boost. The initialization step was fine, but I got the following error with I updated it:

[root@bioinfo-hs-cluster1 modular-boost]# git submodule update
Cloning into 'libs/accumulators'...
remote: Counting objects: 1325, done.
remote: Total 1325 (delta 0), reused 0 (delta 0), pack-reused 1325
Receiving objects: 100% (1325/1325), 1.23 MiB | 325 KiB/s, done.
Resolving deltas: 100% (830/830), done.
Submodule path 'libs/accumulators': checked out 'e0202cdcce09464fd4f7dce7a3f46094ef3ac3ec'
Cloning into 'libs/algorithm'...
remote: Counting objects: 3780, done.
remote: Total 3780 (delta 0), reused 0 (delta 0), pack-reused 3780
Receiving objects: 100% (3780/3780), 3.52 MiB | 985 KiB/s, done.
Resolving deltas: 100% (2311/2311), done.
Submodule path 'libs/algorithm': checked out 'a09963bf93912c1b508e1642bcb8ca09a83eb0ba'
Cloning into 'libs/align'...
**error: The requested URL returned error: 403 while accessing https://github.com/boostorg/align.git/info/refs
fatal: HTTP request failed
Clone of 'https://github.com/boostorg/align.git' into submodule path 'libs/align' failed
error: The requested URL returned error: 403 while accessing https://github.com/boostorg/align.git/info/refsfatal: HTTP request failedClone of 'https://github.com/boostorg/align.git' into submodule path 'libs/align' failed**

So, would you please help to check?

Regards,
Tony

**Comment by tobiasrausch** [comment]
Hi Tony,

Boost is unfortunately very large and occasionally github breaks the connections. You can resume the download with

git submodule update --init --recursive

Alternatively you can install boost using the package manager, e.g. for Ubuntu:

apt-get update
apt-get install -y build-essential g++ git cmake zlib1g-dev ant libbz2-dev libboost-date-time-dev libboost-program-options-dev libboost-system-dev libboost-filesystem-dev libboost-iostreams-dev

-Tobias
